# Generated by Django 4.1 on 2023-04-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Full Time', 'Part Time'), ('Full Time', 'Part Time')], max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('published_at', models.DateField(auto_now=True)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.IntegerField(default=0)),
                ('experiance', models.IntegerField(default=0)),
            ],
        ),
    ]
